name: test dependency

on:
  push:
    branches: [ main ]

jobs:
  installing:
    runs-on: ubuntu-latest

    steps:
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          pip install -e .

      - name: testing
        run: |
          python --version
          python test.py