name: Generate Stats Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  svg-generation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Run using Python 3.10 for consistency and aiohttp
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install -r requirements.txt
          pip install -e .

      - name: testing
        run: |
          python3 --version
          python3 test.py