name: test dependency

on:
  push:
    branches: [ main ]

jobs:
  installing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2         
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip setuptoo
          python -m pip install -r requirements.txt
          pip install -e .

      - name: testing
        run: |
          python --version
          python test.py